### ISSUE TITLE
Use a dictionary for flags.js?

### ISSUE THREAD

**Issue by KopfKrieg** [enwash/pixel-country-picker#14]
Right now we have two arrays, one for the flags, and one for the names of the countries. Wouldn't it be better to use a dictionary here? IMHO it should be easier to maintain.

It could look like this:

```
flags = {
    "Germany": [<here the flags' colours>],
    "USA": [<here the flags' colours>],
    "France": [<here the flags' colours>],
    …
}
```

**Comment by aeonic-dev** [comment]
Was planning on doing this once I merge all the active prs and fix the blank flags

**Comment by aeonic-dev** [comment]
Closing this as I haven't got the time to make any changes. This whole project was thrown together in a few minutes when I got the idea, working on it further is just beating a dead horse.
